vim.opt.smartindent = true
vim.opt.number = true
vim.opt.shiftround = true
vim.opt.undofile = true
vim.opt.relativenumber = true
vim.opt.cursorline = true
vim.opt.tgc = true
vim.opt.cmdheight = 2
vim.opt.signcolumn = 'yes'
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.mouse = 'a'
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.smarttab = true
vim.opt.softtabstop = 0

vim.g.mapleader = " "
